name: auto copy Issues from another repository

on: [push]

env:
  DEVOPS_DIR: devops
  GHSECRET: ${{ secrets.GITHUB_TOKEN }}
  TARGET_REPO: ${{ github.repository }}
  SOURCE_REPO: Modulbereich-Programmierung-Python/CopyIssues
  SCRIPT_REPO: Modulbereich-Programmierung-Python/CopyIssues

jobs:
  show-actor:
    name: show-actor
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${GITHUB_ACTOR}
  copy-issues:
    if: ${{ contains(github.actor, 'marcel') }}
    name: CopyIssues
    runs-on: ubuntu-latest
    steps:
    - name: echo2
      run: echo "success"
